# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Desafio-PicPay-Android-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  # Pods for Desafio-PicPay-Android-iOS
  pod 'MaterialComponents/TextFields'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'Desafio-PicPay-Android-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Desafio-PicPay-Android-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
